services:
  nextjs:
    build:
      context: .
      target: runner
    networks:
      - sist_net
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextjs
    networks:
      - sist_net

networks:
  sist_net:
    driver: bridge